# Generated by Django 2.1.7 on 2019-04-03 23:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 23, 8, 17, 700091, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
